module.exports = [
    {
        id: 0,
        abbreviation: 'State',
        name: 'State of Alaska',
        parent: null,
    },
    {
        id: 1,
        abbreviation: 'Gov',
        name: 'Office of the Governor',
        parent: 0,
    },
    {
        id: 2,
        abbreviation: 'Admin',
        name: 'Department of Administration',
        parent: 0,
    },
    {
        id: 3,
        abbreviation: 'Law',
        name: 'Department of Law',
        parent: 0,
    },
    {
        id: 4,
        abbreviation: 'Rev',
        name: 'Department of Revenue',
        parent: 0,
    },
    {
        id: 5,
        abbreviation: 'E&ED',
        name: 'Department of Education and Early Development',
        parent: 0,
    },
    {
        id: 6,
        abbreviation: 'H&SS',
        name: 'Department of Health and Social Services',
        parent: 0,
    },
    {
        id: 7,
        abbreviation: 'Labor',
        name: 'Department of Labor and Workforce Development',
        parent: 0,
    },
    {
        id: 8,
        abbreviation: 'Commerce',
        name: 'Department of Commerce, Community, and Economic Development',
        parent: 0,
    },
    {
        id: 9,
        abbreviation: 'M&VA',
        name: 'Department of Military and Veterans Affairs',
        parent: 0,
    },
    {
        id: 10,
        abbreviation: 'NatRes',
        name: 'Department of Natural Resources',
        parent: 0,
    },
    {
        id: 11,
        abbreviation: 'FishGm',
        name: 'Department of Fish and Game',
        parent: 0,
    },
    {
        id: 12,
        abbreviation: 'PubSaf',
        name: 'Department of Public Safety',
        parent: 0,
    },
    {
        id: 18,
        abbreviation: 'EnvCon',
        name: 'Department of Environmental Conservation',
        parent: 0,
    },
    {
        id: 20,
        abbreviation: 'Correct',
        name: 'Department of Corrections',
        parent: 0,
    },
    {
        id: 21,
        abbreviation: 'C&RA',
        name: 'Department of Community & Regional Affairs',
        parent: 0,
    },
    {
        id: 25,
        abbreviation: 'Trans',
        name: 'Department of Transportation/Public Facilities',
        parent: 0,
    },
    {
        id: 26,
        abbreviation: 'FCS',
        name: 'Department of Family and Community Services',
        parent: 0,
    },
    {
        id: 27,
        abbreviation: 'OMB',
        name: 'Office of Management and Budget',
        parent: 0,
    },
    {
        id: 28,
        abbreviation: 'Univ',
        name: 'University of Alaska',
        parent: 0,
    },
];
